export * from "@/registry/footer"
export * from "@/registry/authentication";
export * from "@/registry/landing"
export * from "@/registry/about"
export * from "@/registry/company"
export * from "@/registry/faq"
export * from "@/registry/demo"
export * from "@/registry/services"
export * from "@/registry/testimonial"